import { GameCard } from '../types';

// ============================================================
// 소통&갈등관리 모드 카드 (22개) - 재미있는 직장 상황
// ============================================================
export const COMMUNICATION_CARDS: GameCard[] = [
  {
    id: 'CM-001',
    type: 'Communication',
    competency: 'active-listening',
    title: '회의 중 폭탄 발언',
    situation: '팀 회의 중 동료가 갑자기 "솔직히 이 프로젝트, 처음부터 문제 있었잖아요"라고 폭탄 발언을 했습니다. 회의실이 얼어붙었고, 팀장님 표정도 굳었습니다. 하지만 솔직히 맞는 말이기도 합니다.',
    learningPoint: '경청은 불편한 말에도 귀 기울이는 것에서 시작한다',
    choices: [
      { id: 'A', text: '분위기를 위해 얼른 다른 주제로 넘긴다.' },
      { id: 'B', text: '"구체적으로 어떤 부분이 문제라고 생각해?"라고 더 들어본다.' },
      { id: 'C', text: '팀장님 반응을 살피며 조용히 있는다.' },
    ],
  },
  {
    id: 'CM-002',
    type: 'Communication',
    competency: 'clear-expression',
    title: '팀장님의 애매한 지시',
    situation: '"김대리, 그거 적당히 잘 정리해서 갖다줘"라는 지시를 받았습니다. "그거"가 뭔지, "적당히"가 어느 정도인지, 언제까지인지 전혀 모르겠습니다. 근데 팀장님이 바빠 보여서 묻기가 애매합니다.',
    learningPoint: '명확하게 확인하는 것은 일 잘하는 사람의 기본기다',
    choices: [
      { id: 'A', text: '알아서 최선을 다해 정리해본다. 눈치껏 파악하는 것도 능력이다.' },
      { id: 'B', text: '"죄송한데 확인 좀 드려도 될까요?"하며 구체적으로 질문한다.' },
      { id: 'C', text: '옆자리 선배에게 슬쩍 물어본다.' },
    ],
  },
  {
    id: 'CM-003',
    type: 'Communication',
    competency: 'nonverbal-comm',
    title: '화상회의 리액션',
    situation: '화상회의 중 중요한 아이디어를 발표하고 있는데, 화면에 보이는 동료들이 다들 카메라를 끄거나, 딴 곳을 보거나, 하품을 하고 있습니다. 근데 다들 "좋은 의견이에요"라고 채팅은 칩니다.',
    learningPoint: '말보다 행동이 더 많은 것을 말해준다',
    choices: [
      { id: 'A', text: '채팅으로 반응해줬으니 계속 발표한다.' },
      { id: 'B', text: '"혹시 시간이 너무 길면 줄일까요?"라고 확인한다.' },
      { id: 'C', text: '핵심만 빠르게 요약하고 마무리한다.' },
    ],
  },
  {
    id: 'CM-004',
    type: 'Communication',
    competency: 'feedback-giving',
    title: '후배의 황당한 보고서',
    situation: '후배가 작성한 보고서가 도착했는데... 맙소사. 글꼴도 제각각, 숫자는 안 맞고, 결론이 세 번 반복됩니다. 근데 후배가 환하게 웃으며 "어떠세요? 나름 열심히 했는데!"라고 합니다.',
    learningPoint: '피드백은 상대의 성장을 돕는 선물이다',
    choices: [
      { id: 'A', text: '"음... 열심히 했구나..."하고 내가 직접 수정한다.' },
      { id: 'B', text: '잘한 점 하나 말해주고, 개선점을 구체적으로 함께 짚어준다.' },
      { id: 'C', text: '"이건 좀... 다시 해올래?"라고 솔직하게 말한다.' },
    ],
  },
  {
    id: 'CM-005',
    type: 'Communication',
    competency: 'feedback-receiving',
    title: '대선배의 독설',
    situation: '발표를 마쳤는데 대선배가 "요즘 애들은 기본기가 없어. 이게 발표야 수면제야?"라고 모두 앞에서 말합니다. 사람들이 다 쳐다봅니다. 얼굴이 화끈거리고 속에서 뭔가 올라옵니다.',
    learningPoint: '불편한 피드백에서도 성장의 씨앗을 찾을 수 있다',
    choices: [
      { id: 'A', text: '"그럼 어떻게 하면 되는데요?"라고 따진다.' },
      { id: 'B', text: '일단 "알겠습니다"하고, 나중에 구체적인 개선점을 여쭤본다.' },
      { id: 'C', text: '무시하고 자리로 돌아온다. 저런 사람은 상대 안 한다.' },
    ],
  },
  {
    id: 'CM-006',
    type: 'Communication',
    competency: 'conflict-recognition',
    title: '묘한 카톡 이모티콘',
    situation: '요즘 같이 일하는 A와 B 사이가 이상합니다. 단톡방에서 A가 말하면 B가 "ㅇㅇ" 딱 두 글자만. B가 말하면 A는 읽씹. 둘이 같이 있으면 공기가 쌀쌀합니다.',
    learningPoint: '갈등은 눈에 보이기 전에 신호를 보낸다',
    choices: [
      { id: 'A', text: '어른들 일이니 알아서 해결하겠지. 모른 척한다.' },
      { id: 'B', text: '각자 따로 만나 "요즘 어때?"라며 상황을 파악해본다.' },
      { id: 'C', text: '팀 회식을 제안해서 분위기를 풀어본다.' },
    ],
  },
  {
    id: 'CM-007',
    type: 'Communication',
    competency: 'conflict-resolution',
    title: '회의실 냉전',
    situation: '마케팅팀 김과장과 영업팀 이과장이 예산 배분으로 회의실에서 언성을 높이고 있습니다. "영업이 뭘 알아!" "마케팅은 현장을 몰라!" 다른 팀원들은 눈치만 보고 있습니다.',
    learningPoint: '갈등 해결은 입장이 아닌 공동 목표에서 시작한다',
    choices: [
      { id: 'A', text: '상사에게 보고해서 결정을 내려달라고 한다.' },
      { id: 'B', text: '"우리 잠깐, 공통 목표가 뭐였죠?"라며 논점을 정리한다.' },
      { id: 'C', text: '각자 입장을 반씩 절충하는 안을 제안한다.' },
    ],
  },
  {
    id: 'CM-008',
    type: 'Communication',
    competency: 'negotiation',
    title: '야근 떠넘기기',
    situation: '금요일 저녁 6시. 팀장님이 급한 건으로 주말 중 보고서 작성이 필요하다고 합니다. 마침 나와 동료 둘이 남아있습니다. 동료는 "나 이번 주말 결혼식이야"라고 합니다. 나도 예정이 있는데...',
    learningPoint: '협상은 서로의 상황을 이해하고 윈-윈을 찾는 것이다',
    choices: [
      { id: 'A', text: '내가 다 한다. 결혼식보다는 내 일정이 미루기 쉬우니까.' },
      { id: 'B', text: '금요일 밤에 같이 끝내고 주말엔 각자 쉬자고 제안한다.' },
      { id: 'C', text: '내 일정도 말하고, 업무 분담을 협의한다.' },
    ],
  },
  {
    id: 'CM-009',
    type: 'Communication',
    competency: 'mediation',
    title: '두 친구의 곤란한 부탁',
    situation: '친한 두 동료가 서로 싸웠습니다. A는 "B가 먼저 사과해야 해, 걔가 틀렸잖아"라고 하고, B는 "A가 너무한 거 맞잖아, 니가 말 좀 해줘"라고 합니다. 둘 다 내 편을 기대하고 있습니다.',
    learningPoint: '좋은 중재자는 양쪽 편이 아닌 해결의 편에 선다',
    choices: [
      { id: 'A', text: '내 판단에 더 맞는 쪽 편을 들어준다. 솔직한 게 친구다.' },
      { id: 'B', text: '각자 얘기를 들어주고, 직접 대화할 기회를 만들어준다.' },
      { id: 'C', text: '둘 사이에 끼이기 싫으니 중립이라고 선언한다.' },
    ],
  },
  {
    id: 'CM-010',
    type: 'Communication',
    competency: 'emotional-intelligence',
    title: '아이디어 도둑',
    situation: '회의에서 내가 낸 아이디어를 동료가 마치 자기 것처럼 발표하고 있습니다. "제가 생각해봤는데요..."라니! 팀장님이 감탄하며 칭찬합니다. 순간 머리가 하얘지고 화가 치밉니다.',
    learningPoint: '감정을 느끼는 것과 표현하는 것은 다른 문제다',
    choices: [
      { id: 'A', text: '"그거 제 아이디어인데요?"라고 바로 지적한다.' },
      { id: 'B', text: '일단 참고, 회의 후 개인적으로 그 동료와 이야기한다.' },
      { id: 'C', text: '다음부터 아이디어를 먼저 문서로 남겨둔다.' },
    ],
  },
  {
    id: 'CM-011',
    type: 'Communication',
    competency: 'assertiveness',
    title: '무한 업무 폭탄',
    situation: '이미 야근 3일째인데 팀장님이 "김대리, 이것도 좀 해줘"라며 또 업무를 줍니다. 아니, 저 쓰러지기 직전이거든요? 근데 "아니요"라고 하면 열정 없어 보일까 봐...',
    learningPoint: '적절한 자기 주장은 자신과 조직 모두를 위한 것이다',
    choices: [
      { id: 'A', text: '"네..."하고 일단 받는다. 어떻게든 해야지.' },
      { id: 'B', text: '현재 업무 상황을 보여주고 우선순위 조정을 요청한다.' },
      { id: 'C', text: '"해보겠습니다만, 다른 건 좀 미뤄질 수 있어요"라고 말한다.' },
    ],
  },
  {
    id: 'CM-012',
    type: 'Communication',
    competency: 'diplomacy',
    title: '저성과자 면담',
    situation: '팀원 한 명의 실적이 6개월째 팀 최하위입니다. 인사팀에서 경고 조치 전 면담하라고 합니다. 당사자는 나름 열심히 하고 있다고 생각하는 것 같습니다. 어떻게 말해야 상처 주지 않으면서 심각성을 전달할까요?',
    learningPoint: '어려운 메시지일수록 전달 방식이 중요하다',
    choices: [
      { id: 'A', text: '팩트를 직설적으로 말한다. 정확해야 행동이 바뀐다.' },
      { id: 'B', text: '객관적 데이터와 기대치를 공유하고, 함께 개선 방안을 논의한다.' },
      { id: 'C', text: '한 번 더 기회를 주고, 개선 없으면 그때 이야기한다.' },
    ],
  },
  {
    id: 'CM-013',
    type: 'Communication',
    competency: 'cross-cultural-comm',
    title: '해외팀과의 미묘한 오해',
    situation: '미국 본사팀과 화상회의 중입니다. 한국팀의 "검토해 보겠습니다"를 미국팀은 "OK"로 알아들었고, 미국팀의 "That might be challenging"을 한국팀은 "하면 되겠네"로 이해했습니다.',
    learningPoint: '같은 말도 문화에 따라 다르게 해석된다',
    choices: [
      { id: 'A', text: '내가 이해한 대로 진행하고 결과로 확인한다.' },
      { id: 'B', text: '"제가 정확히 이해했는지 확인해도 될까요?"라며 다시 정리한다.' },
      { id: 'C', text: '회의 후 메일로 결정 사항을 정리해서 확인받는다.' },
    ],
  },
  {
    id: 'CM-014',
    type: 'Communication',
    competency: 'difficult-conversation',
    title: '동료의 냄새',
    situation: '옆자리 동료에게서... 냄새가 납니다. 팀원들이 슬슬 힘들어하기 시작했습니다. 누군가는 말해야 하는데 아무도 나서지 않습니다. 저 사람은 전혀 모르는 것 같고요.',
    learningPoint: '어려운 대화도 상대의 존엄성을 지키며 할 수 있다',
    choices: [
      { id: 'A', text: '익명으로 쪽지를 남긴다. 직접 말하기는 너무 곤란하다.' },
      { id: 'B', text: '따로 불러서 "요즘 건강은 괜찮아? 좀 피곤해 보여서"라며 돌려 말한다.' },
      { id: 'C', text: '팀장님께 말씀드려서 처리해달라고 한다.' },
    ],
  },
  {
    id: 'CM-015',
    type: 'Communication',
    competency: 'persuasion',
    title: '반대하는 임원',
    situation: '새 프로젝트를 추진하려는데 핵심 임원이 "그거 안 돼"입니다. 데이터로 설명해도 "느낌이 안 좋아"랍니다. 이 분 동의 없이는 진행이 어렵습니다.',
    learningPoint: '설득은 논리만이 아닌 감정과 관계도 다루는 것이다',
    choices: [
      { id: 'A', text: '더 많은 데이터와 사례를 준비해서 다시 설득한다.' },
      { id: 'B', text: '개인적으로 만나 진짜 우려가 뭔지 들어본다.' },
      { id: 'C', text: '다른 임원들 지지를 먼저 확보한 후 다시 접근한다.' },
    ],
  },
  {
    id: 'CM-016',
    type: 'Communication',
    competency: 'rapport-building',
    title: '새 팀의 아웃사이더',
    situation: '새 팀에 왔는데 기존 팀원들이 너무 친합니다. 점심도 같이 가고, 주말에 모임도 하고. 저한테는 아무도 안 물어봅니다. "신입이니까 알아서 적응하겠지"라고 생각하는 것 같습니다.',
    learningPoint: '관계 형성은 상대방에 대한 진정한 관심에서 시작한다',
    choices: [
      { id: 'A', text: '시간이 해결해줄 것이다. 업무에만 집중한다.' },
      { id: 'B', text: '먼저 커피나 점심을 제안하며 적극적으로 다가간다.' },
      { id: 'C', text: '팀 회식이나 행사에 열심히 참여하면서 자연스럽게 섞인다.' },
    ],
  },
  {
    id: 'CM-017',
    type: 'Communication',
    competency: 'boundary-setting',
    title: '밤 11시 카톡',
    situation: '밤 11시. 팀장님 카톡입니다. "내일 아침 회의 자료 이거 수정해서 줄래?" 침대에 누워있었는데... 매번 이런 식입니다. 워라밸은 어디로...',
    learningPoint: '건강한 경계 설정은 장기적으로 모두에게 좋다',
    choices: [
      { id: 'A', text: '일어나서 수정한다. 상사니까 어쩔 수 없다.' },
      { id: 'B', text: '적절한 때 업무시간 외 연락에 대해 정중히 말씀드린다.' },
      { id: 'C', text: '확인만 하고, 아침에 일찍 출근해서 처리한다.' },
    ],
  },
  {
    id: 'CM-018',
    type: 'Communication',
    competency: 'de-escalation',
    title: '폭주하는 고객',
    situation: '"당장 책임자 나와!" 고객이 매장에서 소리를 지르고 있습니다. 제품 불량 때문인데, 이미 이성을 잃은 상태입니다. 다른 손님들이 쳐다봅니다.',
    learningPoint: '감정이 고조된 상황에서는 문제 해결보다 감정 진정이 먼저다',
    choices: [
      { id: 'A', text: '차분하게 환불 규정을 설명한다. 감정적으로 대응하면 안 된다.' },
      { id: 'B', text: '"불편하셨겠습니다"라며 일단 감정을 인정하고 조용한 곳으로 안내한다.' },
      { id: 'C', text: '바로 상위자를 호출한다. 내 선에서 해결 불가능하다.' },
    ],
  },
  {
    id: 'CM-019',
    type: 'Communication',
    competency: 'perspective-taking',
    title: '이해 안 되는 결정',
    situation: '경영진이 갑자기 재택근무를 전면 금지했습니다. 이유 설명도 없이. 팀원들 불만이 폭발 직전입니다. 솔직히 저도 이해가 안 됩니다.',
    learningPoint: '다른 관점을 이해하려는 노력이 갈등을 줄인다',
    choices: [
      { id: 'A', text: '팀원들과 함께 항의한다. 부당한 건 부당하다고 해야 한다.' },
      { id: 'B', text: '먼저 결정의 배경이 뭔지 알아보고, 팀원들에게 공유한다.' },
      { id: 'C', text: '일단 따르고, 문제점을 데이터로 정리해서 건의한다.' },
    ],
  },
  {
    id: 'CM-020',
    type: 'Communication',
    competency: 'constructive-criticism',
    title: '팀장님의 문제',
    situation: '팀장님의 회의 진행이 문제입니다. 결론 없이 2시간씩, 말 돌리기가 특기. 팀원들이 몰래 한숨을 쉽니다. 누군가는 말해야 하는데...',
    learningPoint: '상위자에게도 건설적인 피드백이 필요할 때가 있다',
    choices: [
      { id: 'A', text: '익명 설문 등 간접적인 방법으로 의견을 전달한다.' },
      { id: 'B', text: '1:1 면담 때 구체적 개선 제안과 함께 조심스럽게 말씀드린다.' },
      { id: 'C', text: '팀장님 스타일이니 맞춰간다. 회의 후 팀원들끼리 정리한다.' },
    ],
  },
  {
    id: 'CM-021',
    type: 'Communication',
    competency: 'apology-forgiveness',
    title: '내 실수로 동료가 야근',
    situation: '제 실수로 데이터가 날아갔고, 동료가 그것 때문에 밤새 야근했습니다. 다음 날 동료 얼굴이 좀비 같습니다. "괜찮아"라고 했지만 이후로 저를 피하는 것 같습니다.',
    learningPoint: '진정한 사과는 변명 없이 책임지고 행동으로 보여주는 것이다',
    choices: [
      { id: 'A', text: '이미 사과했으니 시간이 해결해줄 것이다.' },
      { id: 'B', text: '다시 진심으로 사과하고, 어떻게 보상할 수 있을지 물어본다.' },
      { id: 'C', text: '말로 하기 애매하니 그 동료 업무를 열심히 도와준다.' },
    ],
  },
  {
    id: 'CM-022',
    type: 'Communication',
    competency: 'team-harmony',
    title: '분열된 팀',
    situation: '팀이 두 파벌로 나뉘었습니다. 예전 팀장 편 vs 새 팀장 편. 점심도 따로, 정보 공유도 안 됩니다. 회의 때마다 신경전입니다.',
    learningPoint: '팀 화합은 저절로 이루어지지 않는다',
    choices: [
      { id: 'A', text: '내 업무만 잘하면 된다. 파벌 문제는 팀장이 해결할 일이다.' },
      { id: 'B', text: '양쪽과 두루 교류하며 가교 역할을 한다.' },
      { id: 'C', text: '팀장님께 상황을 공유하고 팀빌딩 활동을 제안한다.' },
    ],
  },
];
