import { CompetencyInfo } from '../types';

// ============================================================
// 역량 정보 목록 (관리자 대시보드용) - 3개 모드 x 22개 = 66개
// ============================================================
export const COMPETENCY_INFO: CompetencyInfo[] = [
  // ========== 핵심가치 모드 22개 (국내 대기업 핵심가치 기반) ==========
  { id: 'people-first', nameKo: '인재제일', nameEn: 'People First', description: '인재가 기업의 가장 중요한 자산', mode: 'CoreValue' },
  { id: 'pursuit-excellence', nameKo: '최고지향', nameEn: 'Pursuit of Excellence', description: '최고를 향한 끊임없는 노력', mode: 'CoreValue' },
  { id: 'leading-change', nameKo: '변화선도', nameEn: 'Leading Change', description: '변화를 두려워하지 않고 앞장서기', mode: 'CoreValue' },
  { id: 'integrity-mgmt', nameKo: '정도경영', nameEn: 'Integrity Management', description: '원칙과 기본에 충실한 경영', mode: 'CoreValue' },
  { id: 'win-win', nameKo: '상생추구', nameEn: 'Win-Win Partnership', description: '함께 성장하는 파트너십', mode: 'CoreValue' },
  { id: 'customer-first', nameKo: '고객 최우선', nameEn: 'Customer First', description: '고객의 가치를 최우선으로', mode: 'CoreValue' },
  { id: 'challenge-execute', nameKo: '도전적 실행', nameEn: 'Challenge & Execute', description: '과감한 도전과 빠른 실행', mode: 'CoreValue' },
  { id: 'communication-collab', nameKo: '소통과 협력', nameEn: 'Communication & Collaboration', description: '열린 소통과 시너지 창출', mode: 'CoreValue' },
  { id: 'respect-talent', nameKo: '인재 존중', nameEn: 'Respect for Talent', description: '구성원의 다양성과 역량 존중', mode: 'CoreValue' },
  { id: 'global-orientation', nameKo: '글로벌 지향', nameEn: 'Global Orientation', description: '세계를 무대로 생각하기', mode: 'CoreValue' },
  { id: 'safety', nameKo: '안전', nameEn: 'Safety', description: '안전은 모든 것의 기본', mode: 'CoreValue' },
  { id: 'ethics', nameKo: '윤리', nameEn: 'Ethics', description: '윤리적 기준을 지키는 행동', mode: 'CoreValue' },
  { id: 'creativity', nameKo: '창의', nameEn: 'Creativity', description: '새로운 아이디어와 방법 추구', mode: 'CoreValue' },
  { id: 'challenge', nameKo: '도전', nameEn: 'Challenge', description: '실패를 두려워하지 않는 도전', mode: 'CoreValue' },
  { id: 'dedication', nameKo: '헌신', nameEn: 'Dedication', description: '맡은 일에 대한 진정한 헌신', mode: 'CoreValue' },
  { id: 'passion', nameKo: '열정', nameEn: 'Passion', description: '일에 대한 뜨거운 열정', mode: 'CoreValue' },
  { id: 'honesty', nameKo: '정직', nameEn: 'Honesty', description: '투명하고 정직한 소통', mode: 'CoreValue' },
  { id: 'professionalism', nameKo: '전문성', nameEn: 'Professionalism', description: '전문가다운 역량과 태도', mode: 'CoreValue' },
  { id: 'responsibility', nameKo: '책임', nameEn: 'Responsibility', description: '결과에 대한 책임감', mode: 'CoreValue' },
  { id: 'innovation', nameKo: '혁신', nameEn: 'Innovation', description: '끊임없는 혁신 추구', mode: 'CoreValue' },
  { id: 'trust', nameKo: '신뢰', nameEn: 'Trust', description: '신뢰받는 조직과 사람', mode: 'CoreValue' },
  { id: 'social-responsibility', nameKo: '사회적 책임', nameEn: 'Social Responsibility', description: '사회에 대한 책임 이행', mode: 'CoreValue' },

  // ========== 소통&갈등관리 모드 22개 ==========
  { id: 'active-listening', nameKo: '적극적 경청', nameEn: 'Active Listening', description: '상대방 말에 집중하고 이해', mode: 'Communication' },
  { id: 'clear-expression', nameKo: '명확한 표현', nameEn: 'Clear Expression', description: '생각을 분명하게 전달', mode: 'Communication' },
  { id: 'nonverbal-comm', nameKo: '비언어적 소통', nameEn: 'Nonverbal Communication', description: '표정, 몸짓을 통한 소통', mode: 'Communication' },
  { id: 'feedback-giving', nameKo: '피드백 제공', nameEn: 'Feedback Giving', description: '건설적 피드백 전달', mode: 'Communication' },
  { id: 'feedback-receiving', nameKo: '피드백 수용', nameEn: 'Feedback Receiving', description: '피드백을 열린 마음으로 수용', mode: 'Communication' },
  { id: 'conflict-recognition', nameKo: '갈등 인식', nameEn: 'Conflict Recognition', description: '갈등 상황 조기 파악', mode: 'Communication' },
  { id: 'conflict-resolution', nameKo: '갈등 해결', nameEn: 'Conflict Resolution', description: '갈등의 건설적 해결', mode: 'Communication' },
  { id: 'negotiation', nameKo: '협상', nameEn: 'Negotiation', description: '윈-윈 합의점 도출', mode: 'Communication' },
  { id: 'mediation', nameKo: '중재', nameEn: 'Mediation', description: '제3자 입장에서 조정', mode: 'Communication' },
  { id: 'emotional-intelligence', nameKo: '감정 지능', nameEn: 'Emotional Intelligence', description: '감정 인식과 조절', mode: 'Communication' },
  { id: 'assertiveness', nameKo: '자기 주장', nameEn: 'Assertiveness', description: '적절히 자신의 의견 표현', mode: 'Communication' },
  { id: 'diplomacy', nameKo: '외교적 소통', nameEn: 'Diplomacy', description: '민감한 상황에서의 소통', mode: 'Communication' },
  { id: 'cross-cultural-comm', nameKo: '다문화 소통', nameEn: 'Cross-Cultural Communication', description: '문화적 차이 이해하며 소통', mode: 'Communication' },
  { id: 'difficult-conversation', nameKo: '어려운 대화', nameEn: 'Difficult Conversations', description: '민감한 주제 다루기', mode: 'Communication' },
  { id: 'persuasion', nameKo: '설득', nameEn: 'Persuasion', description: '논리와 감성으로 설득', mode: 'Communication' },
  { id: 'rapport-building', nameKo: '관계 형성', nameEn: 'Rapport Building', description: '친밀감과 신뢰 구축', mode: 'Communication' },
  { id: 'boundary-setting', nameKo: '경계 설정', nameEn: 'Boundary Setting', description: '건강한 관계 경계 유지', mode: 'Communication' },
  { id: 'de-escalation', nameKo: '긴장 완화', nameEn: 'De-escalation', description: '고조된 감정 진정시키기', mode: 'Communication' },
  { id: 'perspective-taking', nameKo: '관점 수용', nameEn: 'Perspective Taking', description: '다양한 시각에서 바라보기', mode: 'Communication' },
  { id: 'constructive-criticism', nameKo: '건설적 비판', nameEn: 'Constructive Criticism', description: '발전적 비판 제시', mode: 'Communication' },
  { id: 'apology-forgiveness', nameKo: '사과와 용서', nameEn: 'Apology & Forgiveness', description: '진정한 사과와 용서', mode: 'Communication' },
  { id: 'team-harmony', nameKo: '팀 화합', nameEn: 'Team Harmony', description: '팀 분위기 조성', mode: 'Communication' },

  // ========== 신입직원 직장생활 모드 22개 ==========
  { id: 'elevator-etiquette', nameKo: '엘리베이터 예절', nameEn: 'Elevator Etiquette', description: '상석과 버튼 위치 이해', mode: 'NewEmployee' },
  { id: 'honorific-usage', nameKo: '호칭 사용', nameEn: 'Honorific Usage', description: '올바른 직급 호칭 사용', mode: 'NewEmployee' },
  { id: 'dress-code', nameKo: '복장 TPO', nameEn: 'Dress Code', description: '상황에 맞는 복장 선택', mode: 'NewEmployee' },
  { id: 'punctuality', nameKo: '출근 시간 관리', nameEn: 'Punctuality', description: '여유있는 출근 습관', mode: 'NewEmployee' },
  { id: 'leave-etiquette', nameKo: '퇴근 예절', nameEn: 'Leave Etiquette', description: '적절한 퇴근 인사', mode: 'NewEmployee' },
  { id: 'phone-etiquette', nameKo: '전화 예절', nameEn: 'Phone Etiquette', description: '전화 당겨받기와 응대', mode: 'NewEmployee' },
  { id: 'business-card', nameKo: '명함 교환', nameEn: 'Business Card Exchange', description: '명함 주고받기 예절', mode: 'NewEmployee' },
  { id: 'file-management', nameKo: '파일 버전 관리', nameEn: 'File Management', description: '체계적인 파일명 관리', mode: 'NewEmployee' },
  { id: 'office-equipment', nameKo: '사무기기 사용', nameEn: 'Office Equipment', description: '복합기 등 기기 활용', mode: 'NewEmployee' },
  { id: 'meeting-notes', nameKo: '회의록 작성', nameEn: 'Meeting Notes', description: '핵심 위주 회의록 작성', mode: 'NewEmployee' },
  { id: 'schedule-management', nameKo: '일정 관리', nameEn: 'Schedule Management', description: '미팅 일정 조율', mode: 'NewEmployee' },
  { id: 'email-attachment', nameKo: '메일 첨부', nameEn: 'Email Attachment', description: '첨부파일 확인 습관', mode: 'NewEmployee' },
  { id: 'email-cc', nameKo: '수신/참조 구분', nameEn: 'Email CC', description: 'To/CC/BCC 올바른 사용', mode: 'NewEmployee' },
  { id: 'task-clarification', nameKo: '업무지시 확인', nameEn: 'Task Clarification', description: '지시사항 명확히 이해', mode: 'NewEmployee' },
  { id: 'progress-report', nameKo: '중간보고', nameEn: 'Progress Report', description: '적시에 진행상황 공유', mode: 'NewEmployee' },
  { id: 'mistake-handling', nameKo: '실수 대처', nameEn: 'Mistake Handling', description: '실수 인정과 빠른 보고', mode: 'NewEmployee' },
  { id: 'messenger-etiquette', nameKo: '메신저 사용', nameEn: 'Messenger Etiquette', description: '사내 메신저 올바른 활용', mode: 'NewEmployee' },
  { id: 'timing-sense', nameKo: '질문 타이밍', nameEn: 'Timing Sense', description: '상사 상황 파악 후 질문', mode: 'NewEmployee' },
  { id: 'document-writing', nameKo: '문서 작성', nameEn: 'Document Writing', description: '기본적인 보고서 작성', mode: 'NewEmployee' },
  { id: 'verbal-report', nameKo: '구두 보고', nameEn: 'Verbal Report', description: '간결한 구두 보고', mode: 'NewEmployee' },
  { id: 'senior-interaction', nameKo: '선배 응대', nameEn: 'Senior Interaction', description: '선배와의 관계 형성', mode: 'NewEmployee' },
  { id: 'team-dinner', nameKo: '회식 예절', nameEn: 'Team Dinner Etiquette', description: '회식 자리 매너', mode: 'NewEmployee' },
];
